name: Python CI

on:
  push:
    branches:
      - main  # Запускаем только для ветки main
  pull_request:
    branches:
      - main  # Запускаем при PR в ветку main

jobs:
  test:
    runs-on: ubuntu-22.04  # Используем стабильную версию Ubuntu 22.04

    steps:
      - name: Check out code
        uses: actions/checkout@v2  # Проверяем код из репозитория

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # Указываем нужную версию Python

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Устанавливаем зависимости

      - name: Run tests
        run: |
          pytest tests  # Запускаем тесты с помощью pytest
