name: Python CI

on:
  push:
    branches:
      - main  # Запускаем только для ветки main
  pull_request:
    branches:
      - main  # Запускаем при PR в ветку main

jobs:
  test:
    runs-on: ubuntu-22.04  # Используем стабильную версию Ubuntu 22.04

    steps:
      - name: Check out code
        uses: actions/checkout@v2  # Проверяем код из репозитория

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # Указываем нужную версию Python

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Устанавливаем зависимости

      - name: Run tests
        run: |
          pytest tests  # Запускаем тесты с помощью pytest

  deploy:
    runs-on: ubuntu-22.04  # Запускаем на Ubuntu
    needs: test  # Выполняется после успешного прохождения тестов
    if: github.ref == 'refs/heads/main'  # Деплой только из ветки main

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 192.168.x.x >> ~/.ssh/known_hosts

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no baiel@192.168.1.100 "mkdir -p ~/project"
          scp -r ./* baiel@192.168.1.100:~/project/
          ssh -o StrictHostKeyChecking=no user@192.168.x.x <<EOF
            cd ~/project
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            python main.py --no-gui &
          EOF
